/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Car;


import Business.Car.Car;
import Business.Car.CarDirectory;
import Business.Car.CarDriver;
import Business.Car.CarDriverDirectory;
import Business.Validator.Validators1;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author anita
 */
public class CarJPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form DonorJPanel
     */
    
    private JPanel userProcessContainer;
    private CarDirectory carDirectory;
   
    public CarJPanel1(JPanel userProcessContainer,CarDirectory carDirectory) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.carDirectory=carDirectory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dNamejLabel = new javax.swing.JLabel();
        carjTextField = new javax.swing.JTextField();
        createjButton = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        destinationjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sourceJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        costjTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Car  INFORMATION");

        dNamejLabel.setText("Car Name:-");

        createjButton.setText("Create");
        createjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createjButtonActionPerformed(evt);
            }
        });

        backjButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Source");

        jLabel3.setText("Destination");

        jLabel4.setText("Cost");

        costjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costjTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dNamejLabel)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(backjButton1)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sourceJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(carjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destinationjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(createjButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(costjTextField))))
                .addGap(1312, 1312, 1312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dNamejLabel)
                    .addComponent(carjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sourceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(destinationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(costjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createjButton)
                    .addComponent(backjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1087, 1087, 1087))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
      
       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
          
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void createjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createjButtonActionPerformed
        // TODO add your handling code here:
        // Organization organization = (Organization) organizationEmpJComboBox.getSelectedItem();
       
         StringBuilder errorMessage = new StringBuilder();
        Car c= new Car();
    	 
    	if (Validators1.isValidString(carjTextField.getText())) {
    		c.setName(carjTextField.getText());
    	} else {
    		// error message + new line character
    		errorMessage.append("Please enter valid car name").append('\n');
    	}
    	
        
        if (Validators1.isValidString(sourceJTextField.getText())) {
    		c.setSource(sourceJTextField.getText());
    	} else {
    		// error message + new line character
    		errorMessage.append("Please enter valid source name").append('\n');
    	}
    	
        if (Validators1.isValidString(destinationjTextField.getText())) {
    		c.setDestination(destinationjTextField.getText());
    	} else {
    		// error message + new line character
    		errorMessage.append("Please enter valid destination name").append('\n');
    	}
    	
        
         if (Validators1.isValidString(costjTextField.getText())
				&& Validators1.isValidInteger(costjTextField.getText())) {
                c.setCost(Integer.parseInt(costjTextField.getText()));
                
                } else {
    		// error message + new line character
    		errorMessage.append("Please enter valid cost").append('\n');
                
                
                
    	} 
            
		if (errorMessage.length() == 0) {
                    carDirectory.addCar(c);
			JOptionPane.showMessageDialog(null, " Car created succesfully", "Car Created",JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, errorMessage.toString(), "Validation Failed",JOptionPane.ERROR_MESSAGE);
		}
 reset();
        
       // organization.getEmployeeDirectory().createEmployee(name);
    }//GEN-LAST:event_createjButtonActionPerformed
public void reset(){
    carjTextField.setText("");
    sourceJTextField.setText("");
    destinationjTextField.setText("");
    costjTextField.setText("");
    
}
    private void costjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costjTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JTextField carjTextField;
    private javax.swing.JTextField costjTextField;
    private javax.swing.JButton createjButton;
    private javax.swing.JLabel dNamejLabel;
    private javax.swing.JTextField destinationjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField sourceJTextField;
    // End of variables declaration//GEN-END:variables
}
