/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PassengerRole;

import Business.EcoSystem;
import Business.Organization.PassengerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author anita
 */
public class PassengerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PassengerWorkAreaJPanel
     */
    
    private final JPanel userProcessContainer;
    private final PassengerOrganization passengerOrganization;
    private final UserAccount userAccount;
    private final EcoSystem business;
    
    public PassengerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,PassengerOrganization passengerOrganization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.passengerOrganization=passengerOrganization;
        this.userAccount = account;
        this.business=business;
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setjLabel = new javax.swing.JLabel();
        getWeatherjButton = new javax.swing.JButton();
        CaljButton = new javax.swing.JButton();
        bustransportationJButton = new javax.swing.JButton();
        carTransportationjButton = new javax.swing.JButton();
        emailjButton = new javax.swing.JButton();
        TrainjButton = new javax.swing.JButton();
        MapjButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FeedbackjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        getWeatherjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getWeatherjButton.setForeground(new java.awt.Color(255, 102, 102));
        getWeatherjButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\anita\\Desktop\\Project\\waethericon.jpg")); // NOI18N
        getWeatherjButton.setText("Get Weather");
        getWeatherjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getWeatherjButtonActionPerformed(evt);
            }
        });

        CaljButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CaljButton.setForeground(new java.awt.Color(255, 102, 102));
        CaljButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PassengerRole/calculator-icon.jpg"))); // NOI18N
        CaljButton.setText("Calculator");
        CaljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaljButtonActionPerformed(evt);
            }
        });

        bustransportationJButton.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        bustransportationJButton.setForeground(new java.awt.Color(255, 102, 102));
        bustransportationJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PassengerRole/bicon.png"))); // NOI18N
        bustransportationJButton.setText("Bus Transportation");
        bustransportationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bustransportationJButtonActionPerformed(evt);
            }
        });

        carTransportationjButton.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        carTransportationjButton.setForeground(new java.awt.Color(255, 102, 102));
        carTransportationjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PassengerRole/cicon.png"))); // NOI18N
        carTransportationjButton.setText("Car Transportation");
        carTransportationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carTransportationjButtonActionPerformed(evt);
            }
        });

        emailjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailjButton.setForeground(new java.awt.Color(255, 102, 102));
        emailjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PassengerRole/email.png"))); // NOI18N
        emailjButton.setText("Send Email");
        emailjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailjButtonActionPerformed(evt);
            }
        });

        TrainjButton.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        TrainjButton.setForeground(new java.awt.Color(255, 102, 102));
        TrainjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PassengerRole/ticon.png"))); // NOI18N
        TrainjButton.setText("Train Transportation");
        TrainjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainjButtonActionPerformed(evt);
            }
        });

        MapjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MapjButton.setForeground(new java.awt.Color(255, 102, 102));
        MapjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PassengerRole/micon.png"))); // NOI18N
        MapjButton.setText("Maps");
        MapjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapjButtonActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 153, 153));
        jTextField1.setText("Welcome!!!");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PassengerRole/trans.jpg"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        FeedbackjButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        FeedbackjButton.setForeground(new java.awt.Color(255, 102, 102));
        FeedbackjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PassengerRole/feedback-icon-68.jpg"))); // NOI18N
        FeedbackjButton.setText("FeedBack");
        FeedbackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbackjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(889, 889, 889)
                .addComponent(setjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bustransportationJButton))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(carTransportationjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MapjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FeedbackjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getWeatherjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TrainjButton)
                            .addComponent(CaljButton, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(setjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carTransportationjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bustransportationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TrainjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailjButton)
                    .addComponent(MapjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getWeatherjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CaljButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FeedbackjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(152, 152, 152))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getWeatherjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getWeatherjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("GoWeatherJPanel", new GoWeatherJPanel(userProcessContainer));
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_getWeatherjButtonActionPerformed

    private void CaljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaljButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("Calculator", new CalculatorJPanel(userProcessContainer));
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_CaljButtonActionPerformed

    private void bustransportationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bustransportationJButtonActionPerformed
  BusAssignPassengerJPanel bspjp = new BusAssignPassengerJPanel(userProcessContainer,userAccount,passengerOrganization,business);
     userProcessContainer.add("bussaddJPanel",bspjp );
     CardLayout layout = (CardLayout) userProcessContainer.getLayout();
     layout.next(userProcessContainer);
    }//GEN-LAST:event_bustransportationJButtonActionPerformed

    private void carTransportationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carTransportationjButtonActionPerformed

        PassengerAssignJPanel scjp = new PassengerAssignJPanel(userProcessContainer,userAccount,passengerOrganization,business);
        userProcessContainer.add("CarsaddJPanel",scjp );
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_carTransportationjButtonActionPerformed

    private void emailjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailjButtonActionPerformed
      
        EmailJPanel ejp = new EmailJPanel(userProcessContainer);
    
        userProcessContainer.add("EmailJPanel",ejp );
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

       
        
        
    }//GEN-LAST:event_emailjButtonActionPerformed

    private void TrainjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainjButtonActionPerformed
        
        PassengerTrainJPanel scjp = new PassengerTrainJPanel(userProcessContainer,userAccount,passengerOrganization,business);
        userProcessContainer.add("TrainaddJPanel",scjp );
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_TrainjButtonActionPerformed

    private void MapjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapjButtonActionPerformed
        
        
        
try{
    String url="MapsDirection.html";
    java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        
        System.out.println("Connection established");
}
 catch(Exception e){
         
          System.out.println(e);
          
      } 
    }//GEN-LAST:event_MapjButtonActionPerformed

    private void FeedbackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbackjButtonActionPerformed
        FeedbackJPanel cjp = new FeedbackJPanel(userProcessContainer,business,userAccount.getEmployee());
        userProcessContainer.add("Contact ",cjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_FeedbackjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CaljButton;
    private javax.swing.JButton FeedbackjButton;
    private javax.swing.JButton MapjButton;
    private javax.swing.JButton TrainjButton;
    private javax.swing.JButton bustransportationJButton;
    private javax.swing.JButton carTransportationjButton;
    private javax.swing.JButton emailjButton;
    private javax.swing.JButton getWeatherjButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel setjLabel;
    // End of variables declaration//GEN-END:variables
}
