/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PassengerRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PassengerAdminEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.PassengerOrganization;
import Business.Role.PassengerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ritesh
 */
public class PassengerSignUpJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final EcoSystem system;
    
    /**
     * Creates new form PassengerSignUpJPanel
     */
    public PassengerSignUpJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateNetworkComboBox();
    }

    private void populateNetworkComboBox() {
        for (Network network: this.system.getNetworkList()) {
            networkComboBox.addItem(network);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        registerPassengerButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        networkComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Passenger Sign Up");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 151, -1));

        jLabel3.setText("User Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });
        add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 151, -1));

        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });
        add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 151, -1));

        registerPassengerButton.setText("Register");
        registerPassengerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPassengerButtonActionPerformed(evt);
            }
        });
        add(registerPassengerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });
        add(cancelJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jLabel5.setText("Network");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        networkComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboBoxActionPerformed(evt);
            }
        });
        add(networkComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 151, -1));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PassengerRole/welcome.gif"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void registerPassengerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPassengerButtonActionPerformed
        List<Object> validationResult = validateForm();
        if ((boolean)validationResult.get(0)) {
            Network network = (Network) networkComboBox.getSelectedItem();
            String passengerName = nameTextField.getText();
            String userName = userNameTextField.getText();
            String password = passwordTextField.getText();

            PassengerAdminEnterprise paEnt = getOrCreatePassengerAdminEnterprise(network);
            PassengerOrganization pOrg = getOrCreatePassengerOrganization(paEnt);
            Employee passenger = createPassenger(pOrg, passengerName);
            if (passenger != null) {
                passenger.setNetworkId(networkComboBox.getSelectedIndex());
                UserAccount acc = createPassengerUserAccount(pOrg, passenger, userName, password);
                if (acc != null) {
                    JOptionPane.showMessageDialog(null, "Registration Complete! You can now login...", "Success", JOptionPane.INFORMATION_MESSAGE);
                    DB4OUtil.getInstance().storeSystem(system);
                    cancelJButtonActionPerformed(null);
                }
            }
        } else {
            String errMsg = (String) validationResult.get(1);
            JOptionPane.showMessageDialog(null, errMsg, "Alert", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registerPassengerButtonActionPerformed

    private List<Object> validateForm() {
        Network network = (Network) networkComboBox.getSelectedItem();
        String passengerName = nameTextField.getText();
        String userName = userNameTextField.getText();
        String password = passwordTextField.getText();
        
        boolean validReq = true;
        StringBuilder errMsg = new StringBuilder();
        if (network == null) {
            validReq = false;
            errMsg.append("Network must be selected!\n");
        }
        if (passengerName == null || "".equals(passengerName.trim())) {
            validReq = false;
            errMsg.append("Name cannot be empty!\n");
        }
        if (userName == null || "".equals(userName.trim())) {
            validReq = false;
            errMsg.append("User name cannot be empty!\n");
        }
        if (password == null || "".equals(password.trim())) {
            validReq = false;
            errMsg.append("Password cannot be empty!\n");
        }
        return Arrays.asList(new Object[]{validReq, errMsg.toString()});
    }
    
    private PassengerAdminEnterprise getOrCreatePassengerAdminEnterprise(Network network) {
        for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()) {
            if (Enterprise.EnterpriseType.PassengerAdmin.getValue()
                    .equals(enterprise.getEnterpriseType().getValue())) {
                return (PassengerAdminEnterprise) enterprise;
            }
        }

        return (PassengerAdminEnterprise) network.getEnterpriseDirectory().createAndAddEnterprise("PassengerEnterprise", Enterprise.EnterpriseType.PassengerAdmin);
    }
    
    private PassengerOrganization getOrCreatePassengerOrganization(PassengerAdminEnterprise paEnt) {
        for (Organization org: paEnt.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof PassengerOrganization) {
                return (PassengerOrganization) org;
            }
        }
        
        return (PassengerOrganization) paEnt.getOrganizationDirectory().createOrganization(Organization.Type.Passenger);
    }
    
    private Employee createPassenger(PassengerOrganization pOrg, String name) {
        if (doesNotExist(pOrg, name)) {
            return pOrg.getEmployeeDirectory().createEmployee(name);
        } else {
            JOptionPane.showMessageDialog(null, "Passenger name already exists!", "Alert", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    private UserAccount createPassengerUserAccount(PassengerOrganization pOrg, Employee passenger, String userName, String password) {
        if (accountDoesNotExist(pOrg, userName)) {
            return pOrg.getUserAccountDirectory().createUserAccount(userName, password, passenger, new PassengerRole());
        } else {
            JOptionPane.showMessageDialog(null, "User name already exists!", "Alert", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    private boolean doesNotExist(Organization organization, String empName) {
        for(Employee emp: organization.getEmployeeDirectory().getEmployeeList()) {
            if (emp.getName().equalsIgnoreCase(empName)) {
                return false;
            }
        }
        return true;
    }
    
    private boolean accountDoesNotExist(Organization organization, String userName) {
        for (UserAccount acc: organization.getUserAccountDirectory().getUserAccountList()) {
            if (acc.getUsername().equalsIgnoreCase(userName)) {
                return false;
            }
        }
        return true;
    }
    
    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        userProcessContainer.removeAll();
        JPanel blankJP = new JPanel();
        userProcessContainer.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void networkComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_networkComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox networkComboBox;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JButton registerPassengerButton;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
