/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Car.Car;
import Business.EcoSystem;
import Business.Enterprise.CarTransportEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CarDriverOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.CarDriverWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;

/**
 *
 * @author anita
 */
public class ManageSensorJPanel extends javax.swing.JPanel {

    CarTransportEnterprise carTransEnt;
    
    /**
     * Creates new form ManageSensorJPanel
     */
    public ManageSensorJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem business) {
        initComponents();
        for (Network network: business.getNetworkList()) {
            for(Enterprise aEnterprise: network.getEnterpriseDirectory().getEnterpriseList()) {
                if(aEnterprise instanceof CarTransportEnterprise) {
                    carTransEnt = (CarTransportEnterprise) aEnterprise;
                    break;
                }
            }
        }
        
        populateCarComboBox();
    }

    public final void populateCarComboBox(){
        carComboBox.removeAllItems();
        
        for(Car d:carTransEnt.getCarDirectory().getCarList()){
            carComboBox.addItem(d);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        carComboBox = new javax.swing.JComboBox();
        remFuelPctTextField = new javax.swing.JTextField();
        carSpeedTextField = new javax.swing.JTextField();
        tyrePressureTextField = new javax.swing.JTextField();
        engineTemperatureTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        submitSensorReadingsBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sensor Management");

        jLabel2.setText("select car");

        carComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        carComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Speed");

        jLabel4.setText("Fuel %");

        jLabel5.setText("Tyre Pressure");

        jLabel6.setText("Temperature");

        submitSensorReadingsBtn.setText("Submit");
        submitSensorReadingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitSensorReadingsBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Sensor Readings");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tyrePressureTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(carSpeedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(remFuelPctTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(engineTemperatureTextField)))
                            .addComponent(submitSensorReadingsBtn)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(62, 62, 62)
                                .addComponent(carComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(carComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remFuelPctTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tyrePressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(engineTemperatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(submitSensorReadingsBtn)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void carComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carComboBoxActionPerformed

    private void submitSensorReadingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitSensorReadingsBtnActionPerformed
        CarDriverOrganization cdOrg = null;
        
        for(Organization org : carTransEnt.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof CarDriverOrganization) {
                cdOrg = (CarDriverOrganization) org;
                break;
            }
        }
        
        if (cdOrg != null) {
            checkSensorReadings(cdOrg);
        }
    }//GEN-LAST:event_submitSensorReadingsBtnActionPerformed

    private void checkSensorReadings(CarDriverOrganization cdOrg) {
        int remFuel = Integer.parseInt(remFuelPctTextField.getText());
        if (remFuel < 25) {
            CarDriverWorkRequest req = createWorkRequest("Low on fuel. Need to refill soon!");
            cdOrg.getWorkQueue().getWorkRequestList().add(req);
        }
        
        int speed = Integer.parseInt(carSpeedTextField.getText());
        if (speed > 80) {
            CarDriverWorkRequest req = createWorkRequest("You are above speed limit! Reduce your speed");
            cdOrg.getWorkQueue().getWorkRequestList().add(req);
        }
        
        int tyrePressure = Integer.parseInt(tyrePressureTextField.getText());
        if (tyrePressure < 25) {
            CarDriverWorkRequest req = createWorkRequest("Tyres are low on air!");
            cdOrg.getWorkQueue().getWorkRequestList().add(req);
        }
        
        int engineTemp = Integer.parseInt(engineTemperatureTextField.getText());
        if (engineTemp > 50) {
            CarDriverWorkRequest req = createWorkRequest("Engine temp is above normal!");
            cdOrg.getWorkQueue().getWorkRequestList().add(req);
        }
    }

    private CarDriverWorkRequest createWorkRequest(String message) {
        CarDriverWorkRequest request = new CarDriverWorkRequest();
        Car selectedCar =  (Car) carComboBox.getSelectedItem();
        request.setCar(selectedCar);
        request.setSensorMessage(message);
        return request;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox carComboBox;
    private javax.swing.JTextField carSpeedTextField;
    private javax.swing.JTextField engineTemperatureTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField remFuelPctTextField;
    private javax.swing.JButton submitSensorReadingsBtn;
    private javax.swing.JTextField tyrePressureTextField;
    // End of variables declaration//GEN-END:variables

}
