/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CarDriverRole;

import Business.Car.CarDirectory;
import Business.Car.CarDriverDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CarDriverOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author anita
 */
public class CarDriverWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CarDriverWorkAreaJPanel
     */
    private JPanel userProcessContainer;
      private UserAccount userAccount;
       private Enterprise enterprise;
       private CarDriverOrganization carDriverOrganization;
       private CarDriverDirectory carDriverDirectory;
       private CarDirectory carDirectory;
       private EcoSystem business;
    public CarDriverWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,CarDriverOrganization carDriverOrganization,Enterprise enterprise,CarDriverDirectory carDriverDirectory,CarDirectory carDirectory,EcoSystem business) {
        
   
        initComponents();
       
        this.userAccount=userAccount;
        this.enterprise=enterprise;
        this.userProcessContainer=userProcessContainer;
        this.carDriverOrganization=carDriverOrganization;
        this.carDriverDirectory=carDriverDirectory;
        this.carDirectory=carDirectory;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCarsJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        addCarsJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addCarsJButton.setForeground(new java.awt.Color(255, 51, 51));
        addCarsJButton.setText("Add Cars");
        addCarsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarsJButtonActionPerformed(evt);
            }
        });
        add(addCarsJButton);
        addCarsJButton.setBounds(330, 270, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CarDriverRole/car.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(260, 120, 400, 210);
    }// </editor-fold>//GEN-END:initComponents

    private void addCarsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarsJButtonActionPerformed

        CarDriverWorkAreaJPanel1 acp = new CarDriverWorkAreaJPanel1(userProcessContainer,userAccount,carDriverOrganization,enterprise,carDriverDirectory,carDirectory,business);
        userProcessContainer.add("addcars",acp );
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addCarsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCarsJButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
