/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BusAdminRole;

import Business.Bus.Bus;
import Business.Bus.BusDirectory;
import Business.BusDriver.BusDriverDirectory;
import Business.EcoSystem;
import Business.Enterprise.BusTransportEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.BusAdminOrganization;
import Business.Organization.BusDriverOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BusAdminWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anita
 */
public class BusAddJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BusAddJPanel
     */
    private JPanel userProcessContainer;
    private BusAdminOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private BusDirectory busDirectory;
    private BusDriverDirectory busDriverDirectory;
    private Bus bus;
    private EcoSystem business;
    public BusAddJPanel(JPanel userProcessContainer, UserAccount account,BusAdminOrganization organization, Enterprise enterprise,BusDirectory busDirectory,BusDriverDirectory busDriverDirectory,Bus bus,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.busDirectory=busDirectory;
        this.busDriverDirectory=busDriverDirectory;
        this.bus=bus;
        this.business=business;
        
       //populateBusNameComboBox();
        
        populateBusInfoTable();
         refreshTable();
        
        
       
    }
    
     public void refreshTable()
    {
        DefaultTableModel dtm=(DefaultTableModel)BusInfojTable.getModel();
        dtm.setRowCount(0);
        for(Bus b:busDirectory.getBusList())
        {
            Object[] row=new Object[3];
            row[0]=b;
            row[1]=b.getBusSource();
            row[2]=b.getBusDestination();
            
            dtm.addRow(row);
            
        }
    }
    
    
    public void populateBusInfoTable(){
        DefaultTableModel model = (DefaultTableModel) BusInfojTable.getModel();
        
        model.setRowCount(0);
        
         for (Bus b : busDirectory.getBusList()){
        
             Object[] row = new Object[3];
             row[0]=b;
             row[1]=b.getBusSource();
             row[2]=b.getBusDestination();
             
              model.addRow(row);
             
        
        
    }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addBusButton = new javax.swing.JButton();
        refreshTestJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BusInfojTable = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setText("Send Information");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jLabel1.setText("Message");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        messageJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageJTextFieldActionPerformed(evt);
            }
        });
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 340, 30));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, 30));

        jLabel2.setText("Bus Name:-");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        addBusButton.setText("Add Bus");
        addBusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBusButtonActionPerformed(evt);
            }
        });
        add(addBusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        jLabel3.setText("Test  Information:-");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        BusInfojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Bus Name", "Source", "Destination"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BusInfojTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 510, 90));

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        String message = messageJTextField.getText();
         int selectedRow = BusInfojTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }

        BusAdminWorkRequest request = new BusAdminWorkRequest();
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");
        //request.setBus(String.valueOf(selectedRow));
        Bus b = (Bus) BusInfojTable.getValueAt(selectedRow, 0);
        System.out.println(b.getBusSource()+"------------");
        request.setBus(b);
        
        Enterprise ent=null;

        for (Network network: business.getNetworkList()){
            for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                if(enterprise instanceof BusTransportEnterprise){
                    ent = enterprise;
                }
            }
        }

        Organization org = null;
        // Enterprise ent = (PassengerAdminEnterprise)enterprise;

        for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof BusDriverOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null,"Bus Request added","Information",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void messageJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageJTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ViewBusJPanel vbjp = (ViewBusJPanel) component;
        vbjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void addBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBusButtonActionPerformed
        // TODO add your handling code here:
        BusDetailsJPanel bdjp=new BusDetailsJPanel(userProcessContainer,busDirectory,bus);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("carJPanel",bdjp);
        layout.next(userProcessContainer);

    }//GEN-LAST:event_addBusButtonActionPerformed

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed
        
        populateBusInfoTable();
        
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed

        int selectedRow=BusInfojTable.getSelectedRow();
        if(selectedRow>=0)
        {
            int dialogResult=JOptionPane.showConfirmDialog(null, "Please confirm whether to delete","Confirmation",JOptionPane.INFORMATION_MESSAGE);
            if(dialogResult==JOptionPane.YES_OPTION);
            {
                Bus b=(Bus) BusInfojTable.getValueAt(selectedRow,0);
                busDirectory.removeBus(b);
                refreshTable();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select Bus to delete", "delete account", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BusInfojTable;
    private javax.swing.JButton addBusButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
